module.exports = {
  ACTION_SCHEDULED: 'ActionScheduled',
  ACTION_CHALLENGED: 'ActionChallenged',
  ACTION_SETTLED: 'ActionSettled',
  ACTION_DISPUTED: 'ActionDisputed',
  ACTION_ACCEPTED: 'ActionAccepted',
  ACTION_VOIDED: 'ActionVoided',
  ACTION_REJECTED: 'ActionRejected',
  ACTION_CANCELLED: 'ActionCancelled',
  ACTION_EXECUTED: 'ActionExecuted',
  BALANCE_STAKED: 'Staked',
  BALANCE_UNSTAKED: 'Unstaked',
  BALANCE_LOCKED: 'Locked',
  BALANCE_UNLOCKED: 'Unlocked',
  BALANCE_SLAHED: 'Slashed',
  SETTING_CHANGED: 'SettingChanged',
  PERMISSION_CHANGED: 'TokenBalancePermissionChanged',
}
